<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewProjects.aspx.cs" Inherits="Assignment2_TMS.Administrator.ViewProjects1"
    MasterPageFile="~/TMSSite.Master" %>

<asp:Content ContentPlaceHolderID="menu" ID="C1" runat="server">
<p><asp:HyperLink ID="MemberPagesLink" runat="server" NavigateUrl="~/Member/Profile.aspx">Member Function</asp:HyperLink></p>
    <li><a href="AddProject.aspx">Add Project</a></li>
    <li><a href="ViewUsers.aspx">Users</a></li>
    <li><a href="Audit.aspx">Audit Trail</a></li>
</asp:Content>
<asp:Content ContentPlaceHolderID="body" ID="C3" runat="server">
    <asp:UpdatePanel ID="UpdateProjectPanel" runat="server">
        <ContentTemplate>
            <asp:Label ID="messageLabel" runat="server" Text="Error Update Progress!" Visible="false"
                Font-Bold="True" Font-Size="Larger" ForeColor="Red"></asp:Label>
            <asp:GridView ID="ProjectsGridView" runat="server" DataSourceID="projectdb" AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderStyle="Solid"
                DataKeyNames="id" AllowPaging="true" OnRowUpdating="ValidateDataUpdating" OnRowUpdated="UpdateData">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="ProjectID" SortExpression="id" ItemStyle-HorizontalAlign="Center"
                        ReadOnly="True" />
                    <asp:BoundField DataField="projectcode" HeaderText="Code" SortExpression="Code"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="projectname" HeaderText="Name" SortExpression="Name"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="managerid" HeaderText="ManagerId" SortExpression="ManagerId"
                        ItemStyle-HorizontalAlign="Center" />
                </Columns>
                <EmptyDataTemplate>
                    <h2>
                        Empty project records!</h2>
                </EmptyDataTemplate>
            </asp:GridView>
            <asp:SqlDataSource ID="projectdb" runat="server" ConnectionString="Data Source=.\sqlexpress;Initial Catalog='TMSDB';Integrated Security=True;"
                ProviderName="System.Data.SqlClient" DeleteCommandType="StoredProcedure" SelectCommandType="StoredProcedure"
                UpdateCommandType="StoredProcedure" SelectCommand="SPRetrieveProjects" UpdateCommand="SPUpdateProject"
                DeleteCommand="SPDeleteProject">
                <DeleteParameters>
                    <asp:Parameter Name="id" Type="Int32" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="id" Type="Int32" />
                    <asp:Parameter Name="projectcode" Type="String" />
                    <asp:Parameter Name="projectname" Type="String" />
                    <asp:Parameter Name="managerid" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
