<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ViewUsers.aspx.cs" Inherits="Assignment2_TMS.Administrator.ViewUsers"
    MasterPageFile="~/TMSSite.Master" %>

<asp:Content ContentPlaceHolderID="menu" ID="C1" runat="server">
    <p><asp:HyperLink ID="MemberPagesLink" runat="server" NavigateUrl="~/Member/Profile.aspx">Member Function</asp:HyperLink></p>
    <li><a href="AddUser.aspx">Add User</a></li>
    <li><a href="ViewProjects.aspx">Projects</a></li>
    <li><a href="Audit.aspx">Audit Trail</a></li>
</asp:Content>
<asp:Content ContentPlaceHolderID="body" ID="C3" runat="server">
    <asp:UpdatePanel ID="UpdateUserPanel" runat="server">
        <ContentTemplate>
            <asp:Label ID="messageLabel" runat="server" Text="Error Update Progress!" Visible="false" Font-Bold="True" Font-Size="Larger" ForeColor="Red"></asp:Label>
            <asp:GridView ID="UsersGridView" runat="server" DataSourceID="userdb" AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderStyle="Solid"
                DataKeyNames="id" AllowPaging="true" OnRowUpdating="ValidateDataUpdating" OnRowUpdated="UpdateData" OnRowDeleting="CheckDeletingAdminRow">
                <Columns>
                    <asp:BoundField DataField="id" HeaderText="UserID" SortExpression="id" ItemStyle-HorizontalAlign="Center" ReadOnly="True" />
                    <asp:BoundField DataField="username" HeaderText="username" SortExpression="username"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="password" HeaderText="Password" SortExpression="password"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="firstname" HeaderText="Firstname" SortExpression="fname"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="middlename" HeaderText="Middlename" SortExpression="mname"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="lastname" HeaderText="Lastname" SortExpression="lname"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="email" HeaderText="Email" SortExpression="email" ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="managerid" HeaderText="ManagerId" SortExpression="managerid"
                        ItemStyle-HorizontalAlign="Center" />
                    <asp:BoundField DataField="isadmin" HeaderText="isAdmin" SortExpression="isadmin"
                        ItemStyle-HorizontalAlign="Center" ReadOnly="True" Visible="True" />
                </Columns>
                <EmptyDataTemplate>
                    <h2>
                        Empty user records!</h2>
                </EmptyDataTemplate>
            </asp:GridView>
            <asp:SqlDataSource ID="userdb" runat="server" ConnectionString="Data Source=.\sqlexpress;Initial Catalog='TMSDB';Integrated Security=True;"
                ProviderName="System.Data.SqlClient" DeleteCommandType="StoredProcedure" SelectCommandType="StoredProcedure"
                UpdateCommandType="StoredProcedure" SelectCommand="SPRetrievesUsers" UpdateCommand="SPUpdateUser"
                DeleteCommand="SPDeleteUser">
                <DeleteParameters>
                    <asp:Parameter Name="id" Type="Int32" />
                </DeleteParameters>
                <UpdateParameters>
                    <asp:Parameter Name="id" Type="Int32" />
                    <asp:Parameter Name="username" Type="String" />
                    <asp:Parameter Name="password" Type="String" />
                    <asp:Parameter Name="firstname" Type="String" />
                    <asp:Parameter Name="middlename" Type="String" />
                    <asp:Parameter Name="lastname" Type="String" />
                    <asp:Parameter Name="email" Type="String" />
                    <asp:Parameter Name="managerid" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
        </ContentTemplate>
    </asp:UpdatePanel>
</asp:Content>
